version: '3.5'
services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zookeeper_1
    ports:
    - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
    - dubbo-net

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    container_name: zookeeper_2
    ports:
    - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
    - dubbo-net

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    container_name: zookeeper_3
    ports:
    - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
    - dubbo-net

  dubbo-admin:
    image: chenchuxin/dubbo-admin
    container_name: dubbo-admin
    ports:
    - 8080:8080
    links:
    - zoo1
    - zoo2
    - zoo3
    networks:
    - dubbo-net
    environment:
    - dubbo.registry.address=zookeeper://zoo1:2181|zookeeper://zoo2:2181|zookeeper://zoo3:2181
    depends_on:
    - zoo1
    - zoo2
    - zoo3

networks:
  dubbo-net:
    name: dubbo-net
    driver: bridge